### ISSUE TITLE
Error 1603 when trying to install

### ISSUE THREAD

**Issue by ccampozano** [leogcry22/Hades-VegaM#2]
I am using a NUC8i7HVK like you, the maintainer.
I have tried the prepackaged version as well as manually patching with the files you provide in this repository.

The last driver that installs is the beta release from April 2020, direct from AMD. The filename for this is `Win10-Radeon-Software-Adrenalin-2020-Edition-20.4.1-Apr2`. 

If you could look into this, that would be great.

Thank you.

**Comment by leogcry22** [comment]
> I am using a NUC8i7HVK like you, the maintainer.
> I have tried the prepackaged version as well as manually patching with the files you provide in this repository.
> 
> The last driver that installs is the beta release from April 2020, direct from AMD. The filename for this is `Win10-Radeon-Software-Adrenalin-2020-Edition-20.4.1-Apr2`.
> 
> If you could look into this, that would be great.
> 
> Thank you.

I personally recommend you to use the [Display Driver Uninstaller](https://www.wagnardsoft.com) first to make sure there is no conflicts, then just try AMD's [official solution](https://www.amd.com/en/support/kb/faq/gpu-kb1603).
