### ISSUE TITLE
HDMI audio not working

### ISSUE THREAD

**Issue by linlhx** [leogcry22/Hades-VegaM#3]
Radeon Software 21.2.2
In sound control panel HDMI High Definition Audio device displays unplugged.

**Comment by leogcry22** [comment]
> Radeon Software 21.2.2
> In sound control panel HDMI High Definition Audio device displays unplugged.

I'm using miniDP to DP, can confirm audio is working on miniDP and Type-C, I will check this later

**Comment by linlhx** [comment]
HDMI audio only works after I install the Radeon software but before restart OS, or rollback Pci Bus driver, restart, then HDMI audio will work but bluetooth won't work, and after next restart, Pci Bus driver will install again, HDMI audio will not work again.
If uninstall Pci Bus driver amdkmpfd.sys, display driver won't load.
Old version 20.12.1 works though it also has Pci Bus driver,so use old version before it's fixed.

**Comment by leogcry22** [comment]
> HDMI audio only works after I install the Radeon software but before restart OS, or rollback Pci Bus driver, restart, then HDMI audio will work but bluetooth won't work, and after next restart, Pci Bus driver will install again, HDMI audio will not work again.
> If uninstall Pci Bus driver amdkmpfd.sys, display driver won't load.
> Old version 20.12.1 works though it also has Pci Bus driver,so use old version before it's fixed.

Can confirm this is the AMD's bug, not the MOD, it has been fixed in today's latest driver
https://www.amd.com/en/support/kb/release-notes/rn-rad-win-21-2-3

**Comment by leogcry22** [comment]
https://github.com/leogcry22/Hades-VegaM/releases/tag/21.2.3

**Comment by leogcry22** [comment]
https://github.com/leogcry22/Hades-VegaM/releases/tag/21.2.3
