### ISSUE TITLE
can you plz explane how to install this

### ISSUE THREAD

**Issue by vospascal** [leogcry22/Hades-VegaM#6]
i keep getting Error 1603
i copied the files from you to  C:\AMD\Radeon-Software-Adrenalin-2020-21.6.1-Win10-64Bit-June28
then installed it

and removed drivers with DDU v18.0.4.2 driver unstaller

**Comment by vospascal** [comment]
never mind found it :)

**Comment by leogcry22** [comment]
https://www.howtogeek.com/167723/how-to-disable-driver-signature-verification-on-64-bit-windows-8.1-so-that-you-can-install-unsigned-drivers/

**Comment by sypherin** [comment]
I got the 1603 error too at the end, but the driver is installed and working nonetheless so I'm not complaining..
